---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "voting-application.fullname" . }}-data-reader
subjects:
- kind: ServiceAccount
  name: {{ include "voting-application.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "voting-application.fullname" . }}-data-reader
  apiGroup: rbac.authorization.k8s.io